services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-http-test
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Xms256m -Xmx256m
        -XX:+UseG1GC
        -Xlog:gc*,safepoint=info,class+load=info:file=/tmp/jvm.log:time,uptime,level,tags
    volumes:
      - app_logs:/tmp

  dev:
    image: eclipse-temurin:24.0.2_12-jdk
    working_dir: /src
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      GRADLE_USER_HOME: /home/gradle/.gradle 
      HOME: /home/gradle
    volumes:
      - .:/src 
      - gradle_cache:/home/gradle/.gradle

volumes:
  app_logs:
  gradle_cache: